way better i3lock, with a loading image while generating final img

diff --git a/bin/my_i3lock b/bin/my_i3lock
--- a/bin/my_i3lock
+++ b/bin/my_i3lock
@@ -1,22 +1,44 @@
-#! /bin/bash
+#!/bin/zsh
 
-DEBUG_PATH=/tmp/last_lock
+#
+# i3lock options
+#
+# -e ➤ --ignore-empty-password
+# -f ➤ --show-failed-attempts
+# -n ➤ --nofork
+# -i ➤ --image=
+#
 
-function date_time
-{
-	date "+%H:%M:%S"
-}
+i3lock_options=(-f -e)
 
-echo start $(date_time) > $DEBUG_PATH
+loading_img=${HOME}/wallpapers/hacker-virus-loading-computer-1920x1080-blured.png
+final_img=/tmp/screenshot_i3.png
+
+# Screenshot of desktop
+import -window root -quality 0 ${final_img}
 
 pkill unclutter
 
-echo import $(date_time) >> $DEBUG_PATH
-import -window root -resize 10% -resize 1000% -quality 0 /tmp/screenshot_i3.png
+# First loading lock
+i3lock -n ${i3lock_options[@]} -i "$loading_img" &!
+loading_pid=$!
+echo "first is at $loading_pid"
 
-echo i3lock $(date_time) >> $DEBUG_PATH
-i3lock -i /tmp/screenshot_i3.png
+# Generating real lockscreen image
+# ➤ blur
+convert ${final_img} -blur 0x10 ${final_img}
 
-unclutter &
+echo "Real lockscreen generated, killing $loading_pid"
+kill $loading_pid
+echo "Running new i3lock with real lockscreen image"
 
-echo end $(date_time) >> $DEBUG_PATH
+# Real lock
+i3lock ${i3lock_options[@]} -i "${final_img}"
+locker_status=$?
+
+if ! [ "$locker_status" -eq 0 ]; then
+	echo "bad locker_status: $locker_status"
+	i3lock -i "$loading_img";
+fi
+
+unclutter &!
