nix,cfg: Rework tool config base modules
- Rename toolWithConfig -> preConfiguredToolPkg
- Add default `outputs.deps.bins` with bins in `deps.bins`
- Don't require any deps by default
- Improve mergeability of `deps.*` using `ty.anything` instead of `ty.unspecified`
- Rename homeModule outputs (`withDefaults`, + add `specific`)

+ Move zsh base config module in separate file

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -28,10 +28,13 @@ function cfg::check-dependencies()
     fi
   done
   if [[ ${#missing_bins} != 0 ]]; then
-    >&2 echo ":: Missing binaries for this zsh config (expect some broken stuff!)"
+    >&2 echo
+    >&2 echo ":: Missing binaries from PATH for this zsh config (ID: $ZSH_CONFIG_ID)"
     for missing_bin in ${missing_bins[@]}; do
       >&2 echo "::   - $missing_bin"
     done
+    >&2 echo ":: => expect some broken stuff! 😬"
+    >&2 echo
   fi
 }
 
