zsh: from sg config: Disable global pip to avoid mistakes

diff --git a/zsh/fpath/venv::load_funcs b/zsh/fpath/venv::load_funcs
--- a/zsh/fpath/venv::load_funcs
+++ b/zsh/fpath/venv::load_funcs
@@ -1,23 +1,13 @@
 #!/usr/bin/env zsh
 
-function venv_init
-{
-  local venv_dir="${1:-venv}"
-
-  if [[ -d "$venv_dir" ]]; then
-    echo "ERROR: $venv_dir/ directory already exists"
-    return 1
-  fi
-
-  python -m venv "$venv_dir"
-}
+# --- venv functions
 
 function venv__ensure_exists
 {
   local venv_dir="${1:-venv}"
 
   if ! [[ -d "$venv_dir" ]]; then
-    echo "ERROR: $venv_dir/ directory does NOT exist"
+    echo "ERROR: '$venv_dir' directory does NOT exist"
     return 1
   fi
 }
@@ -30,9 +20,31 @@ function venv__ensure_inside
   fi
 }
 
+function venv__ensure_outside
+{
+  if [[ -n "$VIRTUAL_ENV" ]]; then
+    echo "Deactivating active virtual env.."
+    deactivate
+  fi
+}
+
+function venv_init
+{
+  local venv_dir="${1:-venv}"
+
+  if [[ -d "$venv_dir" ]]; then
+    echo "ERROR: '$venv_dir' directory already exists"
+    return 1
+  fi
+
+  python -m venv -- "$venv_dir"
+}
+
 function venv_on
 {
   local venv_dir="${1:-venv}"
+
+  venv__ensure_outside
 
   if ! venv__ensure_exists "$venv_dir"; then
     echo "  Use venv_init to create a venv there."
@@ -62,35 +74,60 @@ function venv_do
   return $ret
 }
 
-function venv_info
-{
-  venv__ensure_inside "$venv_dir" || return 1
-
-  echo "Location: $VIRTUAL_ENV"
-
-  local where_is_pip="$(which pip)"
-  echo "pip is at: $where_is_pip"
-}
-
-# Helper to activate a venv, deactivating an existing one and/or
+# Helper to activate a venv, deactivating an existing one and
 # creating it if necessary.
 function venv_here
 {
   local venv_dir="${1:-venv}"
 
-  if [[ -n "$VIRTUAL_ENV" ]]; then
-    echo "Deactivating active virtual env.."
-    deactivate
-  fi
+  venv__ensure_outside
 
   if ! [[ -d "$venv_dir" ]]; then
-    echo "Venv directory $venv_dir missing, creating venv now.."
+    echo "Venv directory '$venv_dir' missing, creating venv now.."
     venv_init "$venv_dir" || return 1
   fi
 
   echo "Enabling virtual env.."
   venv_on "$venv_dir"
 }
+
+# Helper to reset a venv, deactivating an existing one and recreate
+# the whole virtual env.
+function venv_reset
+{
+  local venv_dir="${1:-venv}"
+
+  venv__ensure_outside
+
+  if [[ -d "$venv_dir" ]]; then
+    echo "Resetting existing virtual env in directory '$venv_dir'.."
+    python -m venv --clear -- "$venv_dir"
+
+    echo "Enabling virtual env.."
+    venv_on "$venv_dir"
+  else
+    venv_here "$venv_dir"
+  fi
+}
+
+# Disable pip unless in a virtual env or --my-env is passed
+function pip
+{
+  if [[ "$1" == "--my-env" ]]; then
+    shift
+    echo "NOTE: if a virtual env is currently active, you'll change that env not your user's."
+    command pip "$@"
+    return $?
+  fi
+
+  if [[ -n "$VIRTUAL_ENV" ]] && [[ `type -p pip` =~ "$VIRTUAL_ENV/bin/pip" ]]; then
+    command pip "$@"
+    return $?
+  fi
+  echo "Nope! 'pip' is disabled globally, use 'pip-my-env' to manage packages in the user env"
+  return 1
+}
+alias pip-my-env="pip --my-env"
 
 # This function only needs to exist, when I call it, this file
 # will get executed and the helper functions will be in scope.
